/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import MODEL.Modelhopdong;
import DAO.Daohopdong;
import View.Viewhopdong;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author Thinkbook 16
 */
public class Viewthemhopdong extends javax.swing.JFrame {

    /**
     * Creates new form Viewthemhopdong
     */
    public Viewthemhopdong() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtMahopdong.setText(createId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMahopdong = new javax.swing.JLabel();
        jLabelNgaybd = new javax.swing.JLabel();
        jLabelThoihan = new javax.swing.JLabel();
        jLabelLoaihopdong = new javax.swing.JLabel();
        jLabelGia = new javax.swing.JLabel();
        jLabelMabql = new javax.swing.JLabel();
        jLabelMacd = new javax.swing.JLabel();
        txtMahopdong = new javax.swing.JTextField();
        txtNgaybd = new javax.swing.JTextField();
        txtThoihan = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtMacd = new javax.swing.JTextField();
        txtMabql = new javax.swing.JTextField();
        CBLoaihopdong = new javax.swing.JComboBox<>();
        btnThemhopdong = new javax.swing.JButton();
        btnResethopdong = new javax.swing.JButton();
        btnQuaylai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 139, 167));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelMahopdong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMahopdong.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMahopdong.setText("Mã Hợp Đồng");

        jLabelNgaybd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNgaybd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNgaybd.setText("Ngày Bắt Đầu");

        jLabelThoihan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelThoihan.setForeground(new java.awt.Color(255, 255, 255));
        jLabelThoihan.setText("Thời Hạn");

        jLabelLoaihopdong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelLoaihopdong.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoaihopdong.setText("Loại Hợp Đồng");

        jLabelGia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGia.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGia.setText("Giá");

        jLabelMabql.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMabql.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMabql.setText("Mã Ban Quản Lý");

        jLabelMacd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMacd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMacd.setText("Mã Cư Dân");

        txtMahopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMahopdongActionPerformed(evt);
            }
        });

        txtNgaybd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaybdActionPerformed(evt);
            }
        });

        CBLoaihopdong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hop dong thue nha", "Hop dong mua nha", " " }));
        CBLoaihopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBLoaihopdongActionPerformed(evt);
            }
        });

        btnThemhopdong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-agreement-new-30 (1).png"))); // NOI18N
        btnThemhopdong.setText("Thêm");
        btnThemhopdong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemhopdong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemhopdongMouseClicked(evt);
            }
        });
        btnThemhopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemhopdongActionPerformed(evt);
            }
        });

        btnResethopdong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-update-30 (1).png"))); // NOI18N
        btnResethopdong.setText("Reset");
        btnResethopdong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResethopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResethopdongActionPerformed(evt);
            }
        });

        btnQuaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-left-50.png"))); // NOI18N
        btnQuaylai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaylaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(111, 111, 111)
                            .addComponent(btnThemhopdong)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnResethopdong))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelLoaihopdong, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(jLabelGia, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(jLabelMabql)
                                .addComponent(jLabelMacd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelNgaybd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelMahopdong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelThoihan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(71, 71, 71)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtThoihan, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CBLoaihopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMahopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNgaybd, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMacd, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMabql, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnQuaylai))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnQuaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMahopdong)
                    .addComponent(txtMahopdong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNgaybd)
                    .addComponent(txtNgaybd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelThoihan)
                    .addComponent(txtThoihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLoaihopdong)
                    .addComponent(CBLoaihopdong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGia)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMacd)
                    .addComponent(txtMacd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMabql)
                    .addComponent(txtMabql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemhopdong)
                    .addComponent(btnResethopdong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMahopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMahopdongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMahopdongActionPerformed

    private void txtNgaybdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaybdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaybdActionPerformed

    private void CBLoaihopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBLoaihopdongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBLoaihopdongActionPerformed

    private void btnThemhopdongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemhopdongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemhopdongMouseClicked

    private void btnThemhopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemhopdongActionPerformed
        try {
            String mahd = txtMahopdong.getText();
            String ngaybd = txtNgaybd.getText();
            String thoihan = txtThoihan.getText();
            String loaihd = CBLoaihopdong.getSelectedItem().toString();
            double gia = Double.parseDouble(txtGia.getText());
            String macd = txtMacd.getText();
            String mabql = txtMabql.getText(); 
            // Create a ModelCanho object with the retrieved data
            Modelhopdong hd = new Modelhopdong(mahd, ngaybd, thoihan, loaihd, gia, macd, mabql);
            Daohopdong them = new Daohopdong();

            // Call the addcanho method of your DAO class to add the Canho
            them.addhopdong(hd);

            // Optionally display a success message or update UI
            JOptionPane.showMessageDialog(null, "Hợp đồng đã được thêm thành công!");

            // Optionally clear input fields or update UI
            Viewhopdong viewhd= new Viewhopdong();
            viewhd.show();
            dispose();

            // Update UI to reflect changes
            // You may need to refresh the table or list displaying the data

        } catch (Exception ex) {
            // Handle any errors or exceptions (e.g., display error message)
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi thêm hợp đồng: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemhopdongActionPerformed

    private void btnResethopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResethopdongActionPerformed
        txtMahopdong.setText("");
        txtNgaybd.setText("");
        txtThoihan.setText("");
        txtGia.setText("");
        txtMacd.setText("");
        txtMabql.setText("");
        
    }//GEN-LAST:event_btnResethopdongActionPerformed

    private void btnQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaylaiActionPerformed
        Viewhopdong viewhd=new Viewhopdong();
        viewhd.show();
        dispose();
    }//GEN-LAST:event_btnQuaylaiActionPerformed
public String createId() {
    ArrayList<Modelhopdong> hopdongAll = Daohopdong.getInstance().selectAll();
    int maxId = 0;
    for (Modelhopdong hopdong : hopdongAll) {
        String MAHOPDONG = hopdong.getMAHOPDONG();
        if (MAHOPDONG.startsWith("HOPDONG")) {
            try {
                int id = Integer.parseInt(MAHOPDONG.replaceAll("[^\\d]", ""));
                if (id > maxId) {
                    maxId = id;
                }
            } catch (NumberFormatException e) {
            }
        }
    }
    return  (String.format("HOPDONG%03d", maxId + 1));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewthemhopdong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewthemhopdong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewthemhopdong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewthemhopdong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewthemhopdong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBLoaihopdong;
    private javax.swing.JButton btnQuaylai;
    private javax.swing.JButton btnResethopdong;
    private javax.swing.JButton btnThemhopdong;
    private javax.swing.JLabel jLabelGia;
    private javax.swing.JLabel jLabelLoaihopdong;
    private javax.swing.JLabel jLabelMabql;
    private javax.swing.JLabel jLabelMacd;
    private javax.swing.JLabel jLabelMahopdong;
    private javax.swing.JLabel jLabelNgaybd;
    private javax.swing.JLabel jLabelThoihan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMabql;
    private javax.swing.JTextField txtMacd;
    private javax.swing.JTextField txtMahopdong;
    private javax.swing.JTextField txtNgaybd;
    private javax.swing.JTextField txtThoihan;
    // End of variables declaration//GEN-END:variables
}
