/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.Daotaikhoan;
import MODEL.Modeltaikhoan;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Thinkbook 16
 */
public class Viewotp extends javax.swing.JFrame {
    String a ;
    String email;
    
    public Viewotp() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public Viewotp(String Otp, String e) {
        initComponents();
        this.setLocationRelativeTo(null);
        a=Otp;
        email = e;
    }
    
    boolean kiemTraLoi() {
        if (txtOtp.getText().equalsIgnoreCase("")) {
            txtOtp.requestFocus();
            JOptionPane.showMessageDialog(this, "Không để trống OTP");
            return false;
        }
        if (txtMkmoi.getText().equalsIgnoreCase("")) {
            txtMkmoi.requestFocus();
            JOptionPane.showMessageDialog(this, "Không để trống mật khẩu");
            return false;
        }
        if (txtXacminh.getText().equalsIgnoreCase("")) {
            txtXacminh.requestFocus();
            JOptionPane.showMessageDialog(this, "Không để trống xác minh mật khẩu");
            return false;
        }       
        return true;
        
}
    boolean kiemtrasl(String sl) {
        return sl.length() == 6 ;
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelCapcha = new javax.swing.JLabel();
        btnXacnhan = new javax.swing.JButton();
        txtMkmoi = new javax.swing.JTextField();
        jLabelCapcha1 = new javax.swing.JLabel();
        txtXacminh = new javax.swing.JTextField();
        txtOtp = new javax.swing.JTextField();
        btnQuaylai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 139, 167));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabelEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Nhập mã OTP");

        jLabelCapcha.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelCapcha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCapcha.setText("Mật khẩu mới");

        btnXacnhan.setBackground(new java.awt.Color(196, 233, 245));
        btnXacnhan.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnXacnhan.setText("Xác nhận");
        btnXacnhan.setBorder(null);
        btnXacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacnhanActionPerformed(evt);
            }
        });

        txtMkmoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMkmoiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMkmoiFocusLost(evt);
            }
        });

        jLabelCapcha1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelCapcha1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCapcha1.setText("Nhập lại mật khẩu mới");

        btnQuaylai.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnQuaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-left-50.png"))); // NOI18N
        btnQuaylai.setBorder(null);
        btnQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaylaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnQuaylai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCapcha)
                    .addComponent(txtMkmoi, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(jLabelCapcha1)
                    .addComponent(txtXacminh)
                    .addComponent(jLabelEmail)
                    .addComponent(txtOtp)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(btnXacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabelEmail))
                    .addComponent(btnQuaylai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtOtp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCapcha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMkmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCapcha1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtXacminh, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacnhanActionPerformed
        if (kiemTraLoi()) {
            if (txtOtp.getText().equals(a) && kiemtrasl(txtMkmoi.getText().trim()) && txtMkmoi.getText().equals(txtMkmoi.getText())) {
                Daotaikhoan tkdao = new Daotaikhoan();
                Modeltaikhoan taikhoan = new Modeltaikhoan();
               
              

                try {
                    taikhoan = tkdao.getTaikhoanByEmail(email);
                } catch (SQLException ex) {
                    Logger.getLogger(Viewotp.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                taikhoan.setPassword(txtMkmoi.getText());     
                
                try {
                    tkdao.update(taikhoan);
                } catch (SQLException ex) {
                    Logger.getLogger(Viewotp.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(Viewotp.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                JOptionPane.showMessageDialog(this, "Cập nhật mật khẩu thành công");
                Viewdangnhap dn = new Viewdangnhap();
                dn.show();
                dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Thông tin không chính xác");
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btnXacnhanActionPerformed

    private void txtMkmoiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMkmoiFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMkmoiFocusGained

    private void txtMkmoiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMkmoiFocusLost
      
    }//GEN-LAST:event_txtMkmoiFocusLost

    private void btnQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaylaiActionPerformed
        Viewquenmk quen = new Viewquenmk();
        quen.show();
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewotp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewotp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewotp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewotp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewotp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuaylai;
    private javax.swing.JButton btnXacnhan;
    private javax.swing.JLabel jLabelCapcha;
    private javax.swing.JLabel jLabelCapcha1;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMkmoi;
    private javax.swing.JTextField txtOtp;
    private javax.swing.JTextField txtXacminh;
    // End of variables declaration//GEN-END:variables
}
