/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.Daocanho;
import DAO.Daohopdong;
import MODEL.Modelcanho;
import MODEL.Modeldienke;
import MODEL.Modeldonghonuoc;
import MODEL.Modelhopdong;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Thinkbook 16
 */
public class Viewdiennuoc extends javax.swing.JFrame {
    String ma ="";
     Modeldienke dien = new Modeldienke();
     Modeldonghonuoc nuoc = new Modeldonghonuoc();
    public Viewdiennuoc() {
        super();
        initComponents();
        setLocationRelativeTo(null);
    }
    public static String formatNumber(double number) {
        // Định dạng số sao cho không có các số 0 ở đầu nhưng tối đa 10 chữ số
        DecimalFormat decimalFormat = new DecimalFormat("#");
        decimalFormat.setMaximumFractionDigits(0); // Không có phần thập phân
        decimalFormat.setMaximumIntegerDigits(10); // Tối đa 10 chữ số

        return decimalFormat.format(number);
    }
    public Viewdiennuoc(Modelcanho a) {
        
        initComponents();
        setLocationRelativeTo(null);
       
        Modelcanho ch = a;
        Modeldienke dk = new Modeldienke();
        Modeldonghonuoc dhn = new Modeldonghonuoc();
        Daocanho chdao = new Daocanho();
         try {
             dhn = chdao.getDHNByMACH(ch.getMACH());
         } catch (SQLException ex) {
             Logger.getLogger(Viewdiennuoc.class.getName()).log(Level.SEVERE, null, ex);
         }
         try {
             dk = chdao.getDKByMACH(ch.getMACH());
         } catch (SQLException ex) {
             Logger.getLogger(Viewdiennuoc.class.getName()).log(Level.SEVERE, null, ex);
         }
         this.dien = dk;
         this.nuoc = dhn;
        
        txtDientruoc.setText(dk.getCST()+ " ");
        txtDiensau.setText(dk.getCSS()+ " ");
        txtGiadien.setText(dk.getGIADIEN()+ " ");
        txtNuoctruoc.setText(dhn.getCST()+ " ");
        txtNuocsau.setText(dhn.getCSS()+ " ");
        txtGianuoc.setText(dhn.getGIANUOC()+ " ");

    }
    
     public Viewdiennuoc(Modelcanho a , String ma) {
        
        initComponents();
        setLocationRelativeTo(null);
        this.ma = ma;
        Modelcanho ch = a;
        Modeldienke dk = new Modeldienke();
        Modeldonghonuoc dhn = new Modeldonghonuoc();
        Daocanho chdao = new Daocanho();
         try {
             dhn = chdao.getDHNByMACH(ch.getMACH());
         } catch (SQLException ex) {
             Logger.getLogger(Viewdiennuoc.class.getName()).log(Level.SEVERE, null, ex);
         }
         try {
             dk = chdao.getDKByMACH(ch.getMACH());
         } catch (SQLException ex) {
             Logger.getLogger(Viewdiennuoc.class.getName()).log(Level.SEVERE, null, ex);
         }
         this.dien = dk;
         this.nuoc = dhn;
        
        txtDientruoc.setText(dk.getCST()+ " ");
        txtDiensau.setText(dk.getCSS()+ " ");
        txtGiadien.setText(dk.getGIADIEN()+ " ");
        txtNuoctruoc.setText(dhn.getCST()+ " ");
        txtNuocsau.setText(dhn.getCSS()+ " ");
        txtGianuoc.setText(dhn.getGIANUOC()+ " ");
        


        
    }
    private int parseInteger(String value) {
    try {
        return (int) Double.parseDouble(value.trim());
    } catch (NumberFormatException e) {
        // Xử lý trường hợp không thể chuyển đổi, có thể ném lại ngoại lệ hoặc trả về giá trị mặc định
        throw new NumberFormatException("Giá trị không hợp lệ: " + value);
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDien = new javax.swing.JLabel();
        jLabelNuoc = new javax.swing.JLabel();
        jLabelCSS = new javax.swing.JLabel();
        jLabelCST = new javax.swing.JLabel();
        jLabelGia = new javax.swing.JLabel();
        jLabelMabql = new javax.swing.JLabel();
        txtDientruoc = new javax.swing.JTextField();
        txtDiensau = new javax.swing.JTextField();
        txtNuoctruoc = new javax.swing.JTextField();
        btnCapnhatdn = new javax.swing.JButton();
        btnResetdn = new javax.swing.JButton();
        btnQuaylai = new javax.swing.JButton();
        txtNuocsau = new javax.swing.JTextField();
        txtGiadien = new javax.swing.JTextField();
        txtGianuoc = new javax.swing.JTextField();
        jLabelHoten1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 139, 167));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelDien.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDien.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDien.setText("Điện");

        jLabelNuoc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNuoc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNuoc.setText("Nước");

        jLabelCSS.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCSS.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCSS.setText("Chỉ số sau");

        jLabelCST.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCST.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCST.setText("Chỉ số trước");

        jLabelGia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabelMabql.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMabql.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMabql.setText("Giá ");

        txtDientruoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtDientruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDientruocActionPerformed(evt);
            }
        });

        txtDiensau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtNuoctruoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCapnhatdn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-update-item (2).png"))); // NOI18N
        btnCapnhatdn.setText("Cập nhật");
        btnCapnhatdn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCapnhatdn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCapnhatdnMouseClicked(evt);
            }
        });
        btnCapnhatdn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatdnActionPerformed(evt);
            }
        });

        btnResetdn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-update-30 (1).png"))); // NOI18N
        btnResetdn.setText("Reset");
        btnResetdn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResetdn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetdnActionPerformed(evt);
            }
        });

        btnQuaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-left-50.png"))); // NOI18N
        btnQuaylai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaylaiActionPerformed(evt);
            }
        });

        txtNuocsau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtGiadien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        txtGianuoc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabelHoten1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelHoten1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoten1.setText("CẬP NHẬT CHỈ SỐ ĐIỆN NƯỚC");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-water-heater-100.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelHoten1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnQuaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelDien)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDientruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabelCST))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelNuoc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                        .addComponent(txtNuoctruoc, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabelCSS, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                            .addComponent(txtDiensau))
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtGiadien, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(23, 23, 23)
                                                .addComponent(jLabelMabql))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNuocsau, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtGianuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(btnCapnhatdn)
                                .addGap(41, 41, 41)
                                .addComponent(btnResetdn)
                                .addGap(39, 39, 39)
                                .addComponent(jLabelGia, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQuaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabelHoten1)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCSS)
                    .addComponent(jLabelCST)
                    .addComponent(jLabelMabql))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiensau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDien)
                    .addComponent(txtDientruoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGiadien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNuocsau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNuoctruoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNuoc)
                    .addComponent(txtGianuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelGia)
                    .addComponent(btnCapnhatdn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnResetdn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDientruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDientruocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDientruocActionPerformed

    private void btnCapnhatdnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCapnhatdnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCapnhatdnMouseClicked

    private void btnCapnhatdnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatdnActionPerformed
    if (ma.equals("")) {    Daocanho ch = new Daocanho();
        
       try {
    this.dien.setCST(parseInteger(txtDientruoc.getText()));
    this.dien.setCSS(parseInteger(txtDiensau.getText()));
    this.nuoc.setCST(parseInteger(txtNuoctruoc.getText()));
    this.nuoc.setCSS(parseInteger(txtNuocsau.getText()));
    if (parseInteger(txtDientruoc.getText())<=parseInteger(txtDiensau.getText()) && parseInteger(txtNuoctruoc.getText())<=parseInteger(txtNuocsau.getText()))
    {
        
    ch.updatenuoc(this.nuoc);
    ch.updatedien(this.dien);
    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
    }
    else 
    {
        JOptionPane.showMessageDialog(this, "Cập nhật thất bại","Lỗi chỉ số",JOptionPane.ERROR_MESSAGE);
    }
    
} catch (SQLException ex) {
    Logger.getLogger(Viewdiennuoc.class.getName()).log(Level.SEVERE, null, ex);
} catch (ParseException ex) {
    Logger.getLogger(Viewdiennuoc.class.getName()).log(Level.SEVERE, null, ex);
} catch (NumberFormatException ex) {
    // Xử lý lỗi NumberFormatException
    JOptionPane.showMessageDialog(this, "Vui lòng nhập các giá trị số nguyên hợp lệ.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
}

// Chuyển hướng tới Viewcanho

    new Viewcanho().setVisible(true);
this.dispose();
} else {
        Daocanho ch = new Daocanho();
        
       try {
    this.dien.setCST(parseInteger(txtDientruoc.getText()));
    this.dien.setCSS(parseInteger(txtDiensau.getText()));
    this.nuoc.setCST(parseInteger(txtNuoctruoc.getText()));
    this.nuoc.setCSS(parseInteger(txtNuocsau.getText()));
    
    if (parseInteger(txtDientruoc.getText())<=parseInteger(txtDiensau.getText()) && parseInteger(txtNuoctruoc.getText())<=parseInteger(txtNuocsau.getText()))
    {
        
    ch.updatenuoc(this.nuoc);
    ch.updatedien(this.dien);
    JOptionPane.showMessageDialog(this, "Cập nhật thành công");
    }
    else 
    {
        JOptionPane.showMessageDialog(this, "Cập nhật thất bại","Lỗi chỉ số",JOptionPane.ERROR_MESSAGE);
    }
} catch (SQLException ex) {
    Logger.getLogger(Viewdiennuoc.class.getName()).log(Level.SEVERE, null, ex);
} catch (ParseException ex) {
    Logger.getLogger(Viewdiennuoc.class.getName()).log(Level.SEVERE, null, ex);
} catch (NumberFormatException ex) {
    // Xử lý lỗi NumberFormatException
    JOptionPane.showMessageDialog(this, "Vui lòng nhập các giá trị số nguyên hợp lệ.", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
}

// Chuyển hướng tới Viewcanho

new Viewcanho(ma).setVisible(true);
this.dispose();
}

    }//GEN-LAST:event_btnCapnhatdnActionPerformed

    private void btnResetdnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetdnActionPerformed
        
        txtDientruoc.setText("");
        txtDiensau.setText("");
        txtNuocsau.setText("");
        txtNuoctruoc.setText("");

    }//GEN-LAST:event_btnResetdnActionPerformed

    private void btnQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaylaiActionPerformed
         if (ma.equals("")) { 
            Viewcanho viewch = new Viewcanho();
            viewch.show();
            dispose();
         }else {
            Viewcanho viewch = new Viewcanho(ma);
            viewch.show();
            dispose();
         }
    }//GEN-LAST:event_btnQuaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewdiennuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewdiennuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewdiennuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewdiennuoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewdiennuoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhatdn;
    private javax.swing.JButton btnQuaylai;
    private javax.swing.JButton btnResetdn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCSS;
    private javax.swing.JLabel jLabelCST;
    private javax.swing.JLabel jLabelDien;
    private javax.swing.JLabel jLabelGia;
    private javax.swing.JLabel jLabelHoten1;
    private javax.swing.JLabel jLabelMabql;
    private javax.swing.JLabel jLabelNuoc;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDiensau;
    private javax.swing.JTextField txtDientruoc;
    private javax.swing.JTextField txtGiadien;
    private javax.swing.JTextField txtGianuoc;
    private javax.swing.JTextField txtNuocsau;
    private javax.swing.JTextField txtNuoctruoc;
    // End of variables declaration//GEN-END:variables
}
