/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.Daohoadon;
import MODEL.Modelhoadon;
import controler.Timhoadon;
import java.awt.Color;
import java.awt.Component;
import java.awt.Desktop;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thinkbook 16
 */
public class Viewthongtinhoadon extends javax.swing.JFrame {
    String ma;
    private DefaultTableModel tblModel;
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    
public static String formatNumber(double number) {
        // Định dạng số sao cho không có các số 0 ở đầu nhưng tối đa 10 chữ số
        DecimalFormat decimalFormat = new DecimalFormat("#");
        decimalFormat.setMaximumFractionDigits(0); // Không có phần thập phân
        decimalFormat.setMaximumIntegerDigits(10); // Tối đa 10 chữ số

        return decimalFormat.format(number);
    }
    
    public Viewthongtinhoadon(String macd) {
        initComponents();
        jTableTthd.setDefaultEditor(Object.class, null);
        initTable();
        this.setLocationRelativeTo(null);
        ma = macd;
        loadDataToTable();
        }
    public final void initTable() {
        tblModel = new DefaultTableModel();
        String[] headerTbl = new String[]{"Mã Hóa Đơn", "Ngày Hóa Đơn", "Trị Giá","Tình Trạng", "Mã Căn Hộ"};
        tblModel.setColumnIdentifiers(headerTbl);
        jTableTthd.setModel(tblModel);
        
        
        
         jTableTthd.setRowHeight(25);
        jTableTthd.setFont(new Font("Arial", Font.PLAIN, 12));

        // Alternating row colors
        jTableTthd.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (isSelected) {
                    c.setBackground(new Color(0, 120, 215)); // Màu nền cho hàng được chọn (thay đổi nếu cần)
                    c.setForeground(Color.WHITE); // Màu chữ cho hàng được chọn (thay đổi nếu cần)
                } else {
                    c.setBackground(row % 2 == 0 ? Color.LIGHT_GRAY : Color.WHITE);
                    c.setForeground(Color.BLACK); // Màu chữ cho hàng không được chọn
                }
                return c;
            }
        });
        jTableTthd.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTableTthd.getColumnModel().getColumn(1).setPreferredWidth(30);
        jTableTthd.getColumnModel().getColumn(2).setPreferredWidth(30);
        jTableTthd.getColumnModel().getColumn(3).setPreferredWidth(30);
        jTableTthd.getColumnModel().getColumn(4).setPreferredWidth(30);
      
    }
    
    
    public MODEL.Modelhoadon getDetail() {
        MODEL.Modelhoadon a = Daohoadon.getInstance().selectById(getHOADONSelect().getMAHD());
        return a;
    }
    public MODEL.Modelhoadon getHOADONSelect() {
        int i_row = jTableTthd.getSelectedRow();
        MODEL.Modelhoadon hoadon = Daohoadon.getInstance().selectAll().get(i_row);
        return hoadon;
    }
     public void loadDataToTable() {
    try {
        Daohoadon daohd = new Daohoadon();
        ArrayList<MODEL.Modelhoadon> arms = daohd.selectInvoicesByMACD(ma);
        tblModel.setRowCount(0);
        for (MODEL.Modelhoadon i : arms ) {
            tblModel.addRow(new Object[]{
                    i.getMAHD(), i.getNGAYHD(),formatNumber(i.getTRIGIA()), i.getTINHTRANG() ,i.getMACH()            
            }
            );
        }
    } catch (Exception e) {
        System.err.println(e.toString());
        
    }
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnXemhd = new javax.swing.JButton();
        btnQuaylai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelGuiyc = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTthd = new javax.swing.JTable();
        labelLichsu = new javax.swing.JLabel();
        btnThanhtoan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(55, 139, 167));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnXemhd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-eye-30.png"))); // NOI18N
        btnXemhd.setText("Xem");
        btnXemhd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXemhd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXemhdMouseClicked(evt);
            }
        });
        btnXemhd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemhdActionPerformed(evt);
            }
        });

        btnQuaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-left-50.png"))); // NOI18N
        btnQuaylai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaylaiActionPerformed(evt);
            }
        });

        labelGuiyc.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        labelGuiyc.setForeground(new java.awt.Color(255, 255, 255));
        labelGuiyc.setText("THÔNG TIN HÓA ĐƠN");

        jTableTthd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Ngày Hóa Đơn", "Trị Giá", "Tình Trạng", "Mã Căn Hộ"
            }
        ));
        jTableTthd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(jTableTthd);

        labelLichsu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        btnThanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-payment-30.png"))); // NOI18N
        btnThanhtoan.setText("Thanh Toán");
        btnThanhtoan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(labelLichsu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnXemhd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThanhtoan)
                        .addGap(89, 89, 89))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnQuaylai)
                        .addGap(66, 66, 66)
                        .addComponent(labelGuiyc)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(labelGuiyc))
                    .addComponent(btnQuaylai))
                .addGap(38, 38, 38)
                .addComponent(labelLichsu)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThanhtoan)
                            .addComponent(btnXemhd))
                        .addGap(43, 43, 43))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemhdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXemhdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXemhdMouseClicked

    private void btnXemhdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemhdActionPerformed
        if (jTableTthd.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn cần xem");
        } else {
            Viewcudancthd frame = new Viewcudancthd(this.ma);
            frame.setVisible(true);
            dispose();
        }  
    
    }//GEN-LAST:event_btnXemhdActionPerformed

    private void btnQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaylaiActionPerformed
        ViewMenucudan menucd=new ViewMenucudan(ma);
        menucd.show();
        dispose();
    }//GEN-LAST:event_btnQuaylaiActionPerformed

    private void btnThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoanActionPerformed
        Viewthanhtoanhd tt = new Viewthanhtoanhd(ma);
        tt.show();     
        dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_btnThanhtoanActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Viewthongtinhoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Viewthongtinhoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Viewthongtinhoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Viewthongtinhoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Viewthongtinhoadon().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuaylai;
    private javax.swing.JButton btnThanhtoan;
    private javax.swing.JButton btnXemhd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableTthd;
    private javax.swing.JLabel labelGuiyc;
    private javax.swing.JLabel labelLichsu;
    // End of variables declaration//GEN-END:variables
}
