/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.Daocudan;
import MODEL.Modelcudan;
import MODEL.Modeltaikhoan;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class ViewMenucudan extends javax.swing.JFrame {
    
    Modelcudan cd = new Modelcudan();
    
    public ViewMenucudan() {
        initComponents();
        this.setLocationRelativeTo(null);
        addHoverEffect(btnttcn);
        addHoverEffect(jButtoncudan);
        addHoverEffectdx(jButtondangxuat);
        addHoverEffect(jButtonyeucau);
    }

    ViewMenucudan(String MACD) {
        initComponents();
        this.setLocationRelativeTo(null);
        cd.setMACD(MACD);        
    }
     private void addHoverEffect(JButton jbutoncanho ) {
        // Customize JButton
        
        jbutoncanho.setBackground(new Color(255, 255, 255));
        jbutoncanho.setForeground(Color.BLACK);
        jbutoncanho.setFocusPainted(false);
        // jbutoncanho.setBorder(new RoundedBorder(20));
        jbutoncanho.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Add hover effect
        jbutoncanho.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jbutoncanho.setBackground(new Color(67, 100, 200));
            }

            public void mouseExited(MouseEvent evt) {
                jbutoncanho.setBackground(new Color(255, 255, 255));
            }
        });
    }
     private void addHoverEffectdx(JButton jbutoncanho ) {
        // Customize JButton
        
        jbutoncanho.setBackground(new Color(55, 139, 167));
        jbutoncanho.setForeground(Color.WHITE);
        jbutoncanho.setFocusPainted(false);
        // jbutoncanho.setBorder(new RoundedBorder(20));
        jbutoncanho.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Add hover effect
        jbutoncanho.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                jbutoncanho.setBackground(new Color(67, 100, 200));
            }

            public void mouseExited(MouseEvent evt) {
                jbutoncanho.setBackground(new Color(55, 139, 167));
            }
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnMenu = new javax.swing.JPanel();
        btnttcn = new javax.swing.JButton();
        jButtoncudan = new javax.swing.JButton();
        jButtonyeucau = new javax.swing.JButton();
        jButtondangxuat = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnMenu.setBackground(new java.awt.Color(55, 139, 167));

        btnttcn.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        btnttcn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-taikhoan-30.png"))); // NOI18N
        btnttcn.setText("THÔNG TIN CÁ NHÂN");
        btnttcn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnttcnActionPerformed(evt);
            }
        });

        jButtoncudan.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtoncudan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-bill-40.png"))); // NOI18N
        jButtoncudan.setText("THÔNG TIN HÓA ĐƠN");
        jButtoncudan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncudanActionPerformed(evt);
            }
        });

        jButtonyeucau.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jButtonyeucau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-email-send-48.png"))); // NOI18N
        jButtonyeucau.setText("GỬI YÊU CẦU");
        jButtonyeucau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonyeucauActionPerformed(evt);
            }
        });

        jButtondangxuat.setBackground(new java.awt.Color(204, 255, 204));
        jButtondangxuat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtondangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-rounded-30.png"))); // NOI18N
        jButtondangxuat.setText("Đăng xuất");
        jButtondangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondangxuatActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Dowload\\2.jpg")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-avatar-96.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-waving-hand-emoji-25.png"))); // NOI18N
        jLabel1.setText("Xin chào cư dân");

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87))
                    .addGroup(jpnMenuLayout.createSequentialGroup()
                        .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtoncudan, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jpnMenuLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(btnttcn, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jButtonyeucau, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnMenuLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jButtondangxuat)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnttcn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButtoncudan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jButtonyeucau, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jButtondangxuat)
                .addGap(93, 93, 93))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonyeucauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonyeucauActionPerformed
        Viewguiyc gui = new Viewguiyc(cd.getMACD());
        gui.show();
        dispose();                // TODO add your handling code here:
    }//GEN-LAST:event_jButtonyeucauActionPerformed

    private void jButtoncudanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncudanActionPerformed
        Viewthongtinhoadon xemtt = new Viewthongtinhoadon(cd.getMACD());
        xemtt.show();
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_jButtoncudanActionPerformed

    private void btnttcnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnttcnActionPerformed
        Viewthongtincanhan viewttcn = new Viewthongtincanhan(cd.getMACD());
        viewttcn.show();
        dispose();
    }//GEN-LAST:event_btnttcnActionPerformed

    private void jButtondangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondangxuatActionPerformed
        Viewdangnhap viewdn = new Viewdangnhap();
        viewdn.show();
        dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_jButtondangxuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewMenucudan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewMenucudan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewMenucudan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewMenucudan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewMenucudan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnttcn;
    private javax.swing.JButton jButtoncudan;
    private javax.swing.JButton jButtondangxuat;
    private javax.swing.JButton jButtonyeucau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jpnMenu;
    // End of variables declaration//GEN-END:variables

    void setCurrentAcc(Modeltaikhoan acc) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
