/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import MODEL.Modelcudan;
import DAO.Daocudan;
import View.Viewcudan;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

   

public class Viewthemcudan extends javax.swing.JFrame {
    
    String ma = "" ;

    /**
     * Creates new form Viewthemcudan
     */
    public Viewthemcudan() {
               initComponents();
        this.setLocationRelativeTo(null);
        txtMacd.setText(createId());
    }
    
    public Viewthemcudan( String ma) {
               initComponents();
        this.setLocationRelativeTo(null);
        this.ma = ma;
        txtMacd.setText(createId());
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMacd = new javax.swing.JLabel();
        jLabelHoten = new javax.swing.JLabel();
        jLabelNgsinh = new javax.swing.JLabel();
        jLabelGioitinh = new javax.swing.JLabel();
        jLabelCccd = new javax.swing.JLabel();
        jLabelLoaicudan = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelSdt = new javax.swing.JLabel();
        txtMacd = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtGioitinh = new javax.swing.JTextField();
        txtCccd = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtLoaicudan = new javax.swing.JTextField();
        btnThemcd = new javax.swing.JButton();
        btnResetcd = new javax.swing.JButton();
        btnQuaylai = new javax.swing.JButton();
        txtNgaysinh = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 139, 167));
        jPanel1.setForeground(null);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelMacd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMacd.setForeground(java.awt.Color.white);
        jLabelMacd.setText("Mã Cư Dân");

        jLabelHoten.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelHoten.setForeground(java.awt.Color.white);
        jLabelHoten.setText("Họ Tên");

        jLabelNgsinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNgsinh.setForeground(java.awt.Color.white);
        jLabelNgsinh.setText("Ngày Sinh");

        jLabelGioitinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGioitinh.setForeground(java.awt.Color.white);
        jLabelGioitinh.setText("Giới Tính");

        jLabelCccd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCccd.setForeground(java.awt.Color.white);
        jLabelCccd.setText("CCCD");

        jLabelLoaicudan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelLoaicudan.setForeground(java.awt.Color.white);
        jLabelLoaicudan.setText("Loại Cư Dân");

        jLabelEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelEmail.setForeground(java.awt.Color.white);
        jLabelEmail.setText("Email");

        jLabelSdt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSdt.setForeground(java.awt.Color.white);
        jLabelSdt.setText("Số Điện Thoại");

        txtMacd.setEditable(false);
        txtMacd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMacdActionPerformed(evt);
            }
        });

        txtHoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHotenActionPerformed(evt);
            }
        });

        btnThemcd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-male-user-30.png"))); // NOI18N
        btnThemcd.setText("Thêm");
        btnThemcd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemcdMouseClicked(evt);
            }
        });
        btnThemcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemcdActionPerformed(evt);
            }
        });

        btnResetcd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-update-30 (1).png"))); // NOI18N
        btnResetcd.setText("Reset");
        btnResetcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetcdActionPerformed(evt);
            }
        });

        btnQuaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-left-50.png"))); // NOI18N
        btnQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaylaiActionPerformed(evt);
            }
        });

        txtNgaysinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaysinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuaylai)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnResetcd)
                            .addGap(96, 96, 96)
                            .addComponent(btnThemcd))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNgsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelGioitinh, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(jLabelCccd, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                .addComponent(jLabelEmail)
                                .addComponent(jLabelLoaicudan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelMacd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelSdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(71, 71, 71)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMacd, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCccd, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLoaicudan, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNgaysinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnQuaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMacd)
                    .addComponent(txtMacd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoten)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNgsinh)
                    .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGioitinh)
                    .addComponent(txtGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCccd)
                    .addComponent(txtCccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSdt)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLoaicudan)
                    .addComponent(txtLoaicudan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemcd)
                    .addComponent(btnResetcd))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMacdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMacdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMacdActionPerformed

    private void txtHotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHotenActionPerformed

    private void btnThemcdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemcdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemcdMouseClicked

    private void btnThemcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemcdActionPerformed
        try {
            String Macd = txtMacd.getText();
            String Hoten =txtHoten.getText();
            String Ngaysinh = txtNgaysinh.getText();
            String Gioitinh = txtGioitinh.getText();
            String Cccd = txtCccd.getText();
            String Sdt = txtSdt.getText();
            String Email = txtEmail.getText();
            String Loaicd = txtLoaicudan.getText();
          
            // Create a ModelCanho object with the retrieved data
            Modelcudan cd = new Modelcudan(Macd, Hoten, Ngaysinh, Gioitinh, Cccd, Sdt, Email, Loaicd);
            Daocudan them = new Daocudan();

            // Call the addcanho method of your DAO class to add the Canho
            them.addcudan(cd);

            // Optionally display a success message or update UI
            JOptionPane.showMessageDialog(null, "Cư dân đã được thêm thành công!");

            // Optionally clear input fields or update UI
            if(ma.equals("")) {
                Viewcudan viewcd= new Viewcudan();
                viewcd.show();
                dispose();
            } else {
                Viewcudan viewcd= new Viewcudan(ma);
                viewcd.show();
                dispose();
            }
            // Update UI to reflect changes
            // You may need to refresh the table or list displaying the data

        } catch (Exception ex) {
            // Handle any errors or exceptions (e.g., display error message)
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi thêm cư dân: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemcdActionPerformed

    private void btnResetcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetcdActionPerformed
        txtHoten.setText("");
        txtNgaysinh.setText("");
        txtGioitinh.setText("");
        txtCccd.setText("");
        txtSdt.setText("");
        txtEmail.setText("");
        txtLoaicudan.setText("");
    
    }//GEN-LAST:event_btnResetcdActionPerformed

    private void btnQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaylaiActionPerformed
        if (ma.equals("")) {
            Viewcudan viewcd=new Viewcudan();
            viewcd.show();
            dispose();
        } else {
            Viewcudan viewcd=new Viewcudan(ma);
            viewcd.show();
            dispose();
        }
    }//GEN-LAST:event_btnQuaylaiActionPerformed

    private void txtNgaysinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaysinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaysinhActionPerformed
public String createId() {
    ArrayList<Modelcudan> cdAll = Daocudan.getInstance().selectAll();
    int maxId = 0;
    for (Modelcudan cd : cdAll) {
        String MACD = cd.getMACD();
        if (MACD.startsWith("CD")) {
            try {
                int id = Integer.parseInt(MACD.replaceAll("[^\\d]", ""));
                if (id > maxId) {
                    maxId = id;
                }
            } catch (NumberFormatException e) {
            }
        }
    }
    return  (String.format("CD%03d", maxId + 1));
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewthemcudan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewthemcudan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewthemcudan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewthemcudan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewthemcudan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuaylai;
    private javax.swing.JButton btnResetcd;
    private javax.swing.JButton btnThemcd;
    private javax.swing.JLabel jLabelCccd;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGioitinh;
    private javax.swing.JLabel jLabelHoten;
    private javax.swing.JLabel jLabelLoaicudan;
    private javax.swing.JLabel jLabelMacd;
    private javax.swing.JLabel jLabelNgsinh;
    private javax.swing.JLabel jLabelSdt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCccd;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGioitinh;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtLoaicudan;
    private javax.swing.JTextField txtMacd;
    private javax.swing.JTextField txtNgaysinh;
    private javax.swing.JTextField txtSdt;
    // End of variables declaration//GEN-END:variables
}
