/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author HP
 */
public class Viewsuacanho extends javax.swing.JFrame {

 
    public Viewsuacanho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtGiaxe2 = new javax.swing.JTextField();
        txtGiaxe4 = new javax.swing.JTextField();
        txtGiaxe6 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabelMach = new javax.swing.JLabel();
        jLabelDientich = new javax.swing.JLabel();
        jLabelLoaiCH = new javax.swing.JLabel();
        jLabelSopngu = new javax.swing.JLabel();
        jLabelSoptam = new javax.swing.JLabel();
        jLabelPhidichvu = new javax.swing.JLabel();
        jLableSlxe = new javax.swing.JLabel();
        jLabelGiathue = new javax.swing.JLabel();
        jLabelTang = new javax.swing.JLabel();
        jLabelGiaxe = new javax.swing.JLabel();
        txtMach = new javax.swing.JTextField();
        txtDientich = new javax.swing.JTextField();
        txtSophongngu = new javax.swing.JTextField();
        txtSophongtam = new javax.swing.JTextField();
        txtTang = new javax.swing.JTextField();
        txtGiathue = new javax.swing.JTextField();
        txtPhidichvu = new javax.swing.JTextField();
        txtSoluongxe = new javax.swing.JTextField();
        CBLoaicanho = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtGiaxe1 = new javax.swing.JTextField();
        txtMacudan = new javax.swing.JTextField();
        txtManhanvien = new javax.swing.JTextField();
        txtMahopdong = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(196, 233, 245));
        jPanel1.setPreferredSize(new java.awt.Dimension(449, 555));

        jLabelMach.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMach.setText("Mã Căn Hộ");

        jLabelDientich.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDientich.setText("Diện tích");

        jLabelLoaiCH.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelLoaiCH.setText("Loại căn hộ");

        jLabelSopngu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSopngu.setText("Số Phòng Ngủ");

        jLabelSoptam.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSoptam.setText("Số Phòng Tắm");

        jLabelPhidichvu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPhidichvu.setText("Phí Dịch Vụ");

        jLableSlxe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLableSlxe.setText("Số Lượng Xe");

        jLabelGiathue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGiathue.setText("Giá Thuê");

        jLabelTang.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTang.setText("Tầng");

        jLabelGiaxe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGiaxe.setText("Giá Xe");

        txtDientich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDientichActionPerformed(evt);
            }
        });

        CBLoaicanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thường", "Studio", " ", " " }));
        CBLoaicanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBLoaicanhoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Mã Cư Dân");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Mã Nhân Viên");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Mã Hợp Đồng");

        jButton1.setText("Sửa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Quay lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMach, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDientich, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLoaiCH, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSopngu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSoptam, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGiathue)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelPhidichvu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLableSlxe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelGiaxe, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDientich)
                            .addComponent(txtSophongngu)
                            .addComponent(txtMach)
                            .addComponent(txtSophongtam)
                            .addComponent(txtTang)
                            .addComponent(txtGiathue)
                            .addComponent(txtPhidichvu)
                            .addComponent(txtSoluongxe)
                            .addComponent(CBLoaicanho, 0, 188, Short.MAX_VALUE)
                            .addComponent(txtGiaxe1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMacudan)
                            .addComponent(txtManhanvien)
                            .addComponent(txtMahopdong)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(259, 259, 259))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(jButton3)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMach)
                    .addComponent(txtMach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDientich)
                    .addComponent(txtDientich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLoaiCH)
                    .addComponent(CBLoaicanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSopngu)
                    .addComponent(txtSophongngu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSoptam)
                    .addComponent(txtSophongtam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTang)
                    .addComponent(txtTang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGiathue)
                    .addComponent(txtGiathue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhidichvu)
                    .addComponent(txtPhidichvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLableSlxe)
                    .addComponent(txtSoluongxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGiaxe)
                    .addComponent(txtGiaxe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMacudan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMahopdong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDientichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDientichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDientichActionPerformed

    private void CBLoaicanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBLoaicanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBLoaicanhoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String mach = txtMach.getText();
            double dienTich = Double.parseDouble(txtDientich.getText());
            String loaich = CBLoaicanho.getSelectedItem().toString();
            int spn = Integer.parseInt(txtSophongngu.getText());
            int spt = Integer.parseInt(txtSophongtam.getText());
            int tang = Integer.parseInt(txtTang.getText());
            double giathue = Double.parseDouble(txtGiathue.getText());
            double phidv = Double.parseDouble(txtPhidichvu.getText());
            double giaxe = Double.parseDouble(txtGiaxe.getText());
            int slxe = Integer.parseInt(txtSoluongxe.getText());
            String macd = txtmacd.getText();
            String manv = txtmanv.getText();
            String mahd = txtmahd.getText();

            // Create a ModelCanho object with the retrieved data
            Modelcanho ch = new Modelcanho(mach, dienTich, loaich, spn, spt, tang, giathue, phidv, giaxe, slxe, macd, manv, mahd);
            Daocanho them = new Daocanho();

            // Call the addcanho method of your DAO class to add the Canho
            them.addcanho(ch);

            // Optionally display a success message or update UI
            JOptionPane.showMessageDialog(null, "Căn hộ đã được thêm thành công!");

            // Optionally clear input fields or update UI
            Viewcanho viewch= new Viewcanho();
            viewch.show();
            dispose();

            // Update UI to reflect changes
            // You may need to refresh the table or list displaying the data

        } catch (Exception ex) {
            // Handle any errors or exceptions (e.g., display error message)
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi thêm căn hộ: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtMach.setText("");
        txtDientich.setText("");
        txtGiathue.setText("");
        txtGiaxe1.setText("");
        txtSophongngu.setText("");
        txtSophongtam.setText("");
        txtTang.setText("");
        txtPhidichvu.setText("");
        txtSoluongxe.setText("");
        txtMacudan.setText("");
        txtManhanvien.setText("");
        txtMahopdong.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Viewcanho viewch=new Viewcanho();
        viewch.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewsuacanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewsuacanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewsuacanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewsuacanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewsuacanho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBLoaicanho;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelDientich;
    private javax.swing.JLabel jLabelGiathue;
    private javax.swing.JLabel jLabelGiaxe;
    private javax.swing.JLabel jLabelLoaiCH;
    private javax.swing.JLabel jLabelMach;
    private javax.swing.JLabel jLabelPhidichvu;
    private javax.swing.JLabel jLabelSopngu;
    private javax.swing.JLabel jLabelSoptam;
    private javax.swing.JLabel jLabelTang;
    private javax.swing.JLabel jLableSlxe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDientich;
    private javax.swing.JTextField txtGiathue;
    private javax.swing.JTextField txtGiaxe1;
    private javax.swing.JTextField txtGiaxe2;
    private javax.swing.JTextField txtGiaxe4;
    private javax.swing.JTextField txtGiaxe6;
    private javax.swing.JTextField txtMach;
    private javax.swing.JTextField txtMacudan;
    private javax.swing.JTextField txtMahopdong;
    private javax.swing.JTextField txtManhanvien;
    private javax.swing.JTextField txtPhidichvu;
    private javax.swing.JTextField txtSoluongxe;
    private javax.swing.JTextField txtSophongngu;
    private javax.swing.JTextField txtSophongtam;
    private javax.swing.JTextField txtTang;
    // End of variables declaration//GEN-END:variables
}
