/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import DAO.Daocudan;
import MODEL.Modelcudan;
import javax.swing.JOptionPane;
import View.Viewcudan;
import java.awt.Frame;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextField;



public class Viewsuacudan extends javax.swing.JFrame {
    
    String ma = "";
    
    public Viewsuacudan() {
        super();
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public Viewsuacudan(Modelcudan c) {
        super();  // gọi constructor của JFrame
        initComponents();
        setLocationRelativeTo(null);
        Modelcudan cd = c;
        
        txtMacd.setText(cd.getMACD().trim());
        txtHoten.setText(cd.getHoten().trim());
        txtNgaysinh.setText(cd.getNgsinh().trim());
        txtGioitinh.setText(cd.getGioitinh().trim());
        txtCccd.setText(cd.getCccd().trim());
        txtSdt.setText(cd.getSdt().trim());
        txtEmail.setText(cd.getEmail().trim());
        txtLoaicudan.setText(cd.getLoaicd().trim());  
    }
    
     public Viewsuacudan(Modelcudan c , String ma) {
        super();  // gọi constructor của JFrame
        initComponents();
        setLocationRelativeTo(null);
        this.ma =ma ;
        Modelcudan cd = c;
        
        txtMacd.setText(cd.getMACD().trim());
        txtHoten.setText(cd.getHoten().trim());
        txtNgaysinh.setText(cd.getNgsinh().trim());
        txtGioitinh.setText(cd.getGioitinh().trim());
        txtCccd.setText(cd.getCccd().trim());
        txtSdt.setText(cd.getSdt().trim());
        txtEmail.setText(cd.getEmail().trim());
        txtLoaicudan.setText(cd.getLoaicd().trim());  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMacd = new javax.swing.JLabel();
        jLabelHoten = new javax.swing.JLabel();
        jLabelNgsinh = new javax.swing.JLabel();
        jLabelGioitinh = new javax.swing.JLabel();
        jLabelCccd = new javax.swing.JLabel();
        jLabelLoaicudan = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelSdt = new javax.swing.JLabel();
        txtMacd = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtGioitinh = new javax.swing.JTextField();
        txtCccd = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtLoaicudan = new javax.swing.JTextField();
        btnSuacd = new javax.swing.JButton();
        btnResetcd = new javax.swing.JButton();
        btnQuaylai = new javax.swing.JButton();
        txtNgaysinh = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 139, 167));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelMacd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMacd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMacd.setText("Mã Cư Dân");

        jLabelHoten.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelHoten.setForeground(new java.awt.Color(255, 255, 255));
        jLabelHoten.setText("Họ Tên");

        jLabelNgsinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNgsinh.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNgsinh.setText("Ngày Sinh");

        jLabelGioitinh.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGioitinh.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGioitinh.setText("Giới Tính");

        jLabelCccd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelCccd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCccd.setText("CCCD");

        jLabelLoaicudan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelLoaicudan.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoaicudan.setText("Loại Cư Dân");

        jLabelEmail.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(255, 255, 255));
        jLabelEmail.setText("Email");

        jLabelSdt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSdt.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSdt.setText("Số Điện Thoại");

        txtMacd.setEditable(false);
        txtMacd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMacdActionPerformed(evt);
            }
        });

        txtHoten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHotenActionPerformed(evt);
            }
        });

        btnSuacd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-update-item (2).png"))); // NOI18N
        btnSuacd.setText("Sửa");
        btnSuacd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuacdMouseClicked(evt);
            }
        });
        btnSuacd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuacdActionPerformed(evt);
            }
        });

        btnResetcd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-update-30 (1).png"))); // NOI18N
        btnResetcd.setText("Reset");
        btnResetcd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetcdActionPerformed(evt);
            }
        });

        btnQuaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-left-50.png"))); // NOI18N
        btnQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaylaiActionPerformed(evt);
            }
        });

        txtNgaysinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaysinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNgsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelGioitinh, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(jLabelCccd, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                                    .addComponent(jLabelEmail)
                                    .addComponent(jLabelLoaicudan, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelMacd, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSdt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(btnSuacd)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtHoten, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(txtGioitinh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMacd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCccd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSdt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLoaicudan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgaysinh)
                            .addComponent(btnResetcd)))
                    .addComponent(btnQuaylai))
                .addGap(81, 81, 81))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnQuaylai)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMacd)
                    .addComponent(txtMacd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoten)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNgsinh)
                    .addComponent(txtNgaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGioitinh)
                    .addComponent(txtGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCccd)
                    .addComponent(txtCccd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSdt)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLoaicudan)
                    .addComponent(txtLoaicudan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuacd)
                    .addComponent(btnResetcd))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMacdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMacdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMacdActionPerformed

    private void txtHotenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHotenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHotenActionPerformed

    private void btnSuacdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuacdMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuacdMouseClicked

    private void btnSuacdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuacdActionPerformed
        Daocudan cd = new Daocudan();
        Modelcudan s = new Modelcudan();
        
        s.setMACD(txtMacd.getText());
        s.setHoten(txtHoten.getText());
        s.setNgsinh(txtNgaysinh.getText());
        s.setGioitinh(txtGioitinh.getText());
        s.setCccd(txtCccd.getText());
        s.setSdt(txtSdt.getText());
        s.setEmail(txtEmail.getText());
        s.setLoaicd (txtLoaicudan.getText());
             
        try {
            cd.update(s);
        } catch (SQLException ex) {
            Logger.getLogger(Viewsuacudan.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Viewsuacudan.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (ma.equals("")) {
            new Viewcudan().setVisible(true);
            this.dispose();
        } else {
            new Viewcudan(ma).setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnSuacdActionPerformed

    private void btnResetcdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetcdActionPerformed
        txtHoten.setText("");
        txtNgaysinh.setText("");
        txtGioitinh.setText("");
        txtCccd.setText("");
        txtSdt.setText("");
        txtEmail.setText("");
        txtLoaicudan.setText("");
    }//GEN-LAST:event_btnResetcdActionPerformed

    private void btnQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaylaiActionPerformed
        if (ma.equals("")) {
            Viewcudan viewcd=new Viewcudan();
            viewcd.show();
            dispose();
        } else {
            Viewcudan viewcd=new Viewcudan(ma);
            viewcd.show();
            dispose();
        }
    }//GEN-LAST:event_btnQuaylaiActionPerformed

    private void txtNgaysinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaysinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaysinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewsuacudan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewsuacudan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewsuacudan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewsuacudan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewsuacudan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuaylai;
    private javax.swing.JButton btnResetcd;
    private javax.swing.JButton btnSuacd;
    private javax.swing.JLabel jLabelCccd;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGioitinh;
    private javax.swing.JLabel jLabelHoten;
    private javax.swing.JLabel jLabelLoaicudan;
    private javax.swing.JLabel jLabelMacd;
    private javax.swing.JLabel jLabelNgsinh;
    private javax.swing.JLabel jLabelSdt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCccd;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGioitinh;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtLoaicudan;
    private javax.swing.JTextField txtMacd;
    private javax.swing.JTextField txtNgaysinh;
    private javax.swing.JTextField txtSdt;
    // End of variables declaration//GEN-END:variables
}
