/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import DAO.Daohoadon;
import MODEL.Modelhoadon;
import MODEL.Modelcthd;
import javax.swing.JOptionPane;
import View.Viewhoadon;
import java.awt.Frame;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextField;



public class Viewcthd extends javax.swing.JFrame {
    
    String ma = "" ; 
    String manv ="" ;
    public Viewcthd() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public static String formatNumber(double number) {
        // Định dạng số sao cho không có các số 0 ở đầu nhưng tối đa 10 chữ số
        DecimalFormat decimalFormat = new DecimalFormat("#");
        decimalFormat.setMaximumFractionDigits(0); // Không có phần thập phân
        decimalFormat.setMaximumIntegerDigits(10); // Tối đa 10 chữ số

        return decimalFormat.format(number);
    }
    
    public Viewcthd(String ma) {
        initComponents();
        setLocationRelativeTo(null);
        this.ma = ma;
        Daohoadon dhd = new Daohoadon();
        Modelhoadon hd = dhd.selectById(ma);
        Modelcthd ct = new Modelcthd();
        try {
            ct = dhd.getXEMCTHDByMAHD(hd.getMAHD());
        } catch (SQLException ex) {
            Logger.getLogger(Viewcthd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtMahd.setText(ct.getMAHD().trim());
        txtGiathue.setText(formatNumber(ct.getGIATHUE()) + " ");
        txtPhixe.setText(formatNumber(ct.getPHIXE()) + " ");
        txtPhidv.setText(formatNumber(ct.getPHIDV()) + " ");
        txtTiendien.setText(formatNumber(ct.getTIENDIEN()) + " ");
        txtTiennuoc.setText(formatNumber(ct.getTIENNUOC()) + " ");
        txtTongtien.setText(formatNumber(hd.getTRIGIA()) + " ");
       
    }
    
     public Viewcthd(String ma , String manv) {
        initComponents();
        setLocationRelativeTo(null);
        this.ma = ma;
        this.manv = manv;
        Daohoadon dhd = new Daohoadon();
        Modelhoadon hd = dhd.selectById(ma);
        Modelcthd ct = new Modelcthd();
        try {
            ct = dhd.getXEMCTHDByMAHD(hd.getMAHD());
        } catch (SQLException ex) {
            Logger.getLogger(Viewcthd.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        txtMahd.setText(ct.getMAHD().trim());
        txtGiathue.setText(formatNumber(ct.getGIATHUE()) + " ");
        txtPhixe.setText(formatNumber(ct.getPHIXE()) + " ");
        txtPhidv.setText(formatNumber(ct.getPHIDV()) + " ");
        txtTiendien.setText(formatNumber(ct.getTIENDIEN()) + " ");
        txtTiennuoc.setText(formatNumber(ct.getTIENNUOC()) + " ");
        txtTongtien.setText(formatNumber(hd.getTRIGIA()) + " ");
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMahd = new javax.swing.JLabel();
        jLabelGiathue = new javax.swing.JLabel();
        jLabelPhixe = new javax.swing.JLabel();
        jLabelPhidv = new javax.swing.JLabel();
        jLabelTiendien = new javax.swing.JLabel();
        jLabelTongtien = new javax.swing.JLabel();
        jLabelTiennuoc = new javax.swing.JLabel();
        txtMahd = new javax.swing.JTextField();
        txtGiathue = new javax.swing.JTextField();
        txtPhixe = new javax.swing.JTextField();
        txtTiendien = new javax.swing.JTextField();
        txtTiennuoc = new javax.swing.JTextField();
        txtTongtien = new javax.swing.JTextField();
        btnQuaylai = new javax.swing.JButton();
        txtPhidv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 139, 167));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelMahd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMahd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMahd.setText("Mã Hóa Đơn");

        jLabelGiathue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGiathue.setForeground(new java.awt.Color(255, 255, 255));
        jLabelGiathue.setText("Giá Thuê");

        jLabelPhixe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPhixe.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPhixe.setText("Phí Xe");

        jLabelPhidv.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPhidv.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPhidv.setText("Phí Dịch Vụ");

        jLabelTiendien.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTiendien.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTiendien.setText("Tiền Điện");

        jLabelTongtien.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTongtien.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTongtien.setText("Tổng Tiền");

        jLabelTiennuoc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTiennuoc.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTiennuoc.setText("Tiền Nước");

        txtMahd.setEditable(false);
        txtMahd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMahdActionPerformed(evt);
            }
        });

        txtGiathue.setEditable(false);
        txtGiathue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiathueActionPerformed(evt);
            }
        });

        txtPhixe.setEditable(false);

        txtTiendien.setEditable(false);

        txtTiennuoc.setEditable(false);

        txtTongtien.setEditable(false);

        btnQuaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-left-50.png"))); // NOI18N
        btnQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaylaiActionPerformed(evt);
            }
        });

        txtPhidv.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-bill-40.png"))); // NOI18N
        jLabel1.setText("Chi tiết hóa dơn");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelPhidv, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jLabelTiendien, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jLabelTongtien)
                            .addComponent(jLabelTiennuoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelGiathue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelMahd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPhixe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPhixe, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(txtMahd, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(txtGiathue, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(txtTiendien, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(txtTiennuoc, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(txtTongtien, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                            .addComponent(txtPhidv)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQuaylai)
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQuaylai)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMahd)
                    .addComponent(txtMahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGiathue)
                    .addComponent(txtGiathue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhixe)
                    .addComponent(txtPhixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhidv)
                    .addComponent(txtPhidv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTiendien)
                    .addComponent(txtTiendien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTiennuoc)
                    .addComponent(txtTiennuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTongtien)
                    .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMahdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMahdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMahdActionPerformed

    private void txtGiathueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiathueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiathueActionPerformed

    private void btnQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaylaiActionPerformed
        if(ma.equals("")) {
            Viewhoadon hdview = new Viewhoadon();
            hdview.show();
            dispose();
        } else {
            Viewhoadon hdview=new Viewhoadon(manv);
            hdview.show();
            dispose();
        }
    }//GEN-LAST:event_btnQuaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewcthd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewcthd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewcthd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewcthd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewcthd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuaylai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelGiathue;
    private javax.swing.JLabel jLabelMahd;
    private javax.swing.JLabel jLabelPhidv;
    private javax.swing.JLabel jLabelPhixe;
    private javax.swing.JLabel jLabelTiendien;
    private javax.swing.JLabel jLabelTiennuoc;
    private javax.swing.JLabel jLabelTongtien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtGiathue;
    private javax.swing.JTextField txtMahd;
    private javax.swing.JTextField txtPhidv;
    private javax.swing.JTextField txtPhixe;
    private javax.swing.JTextField txtTiendien;
    private javax.swing.JTextField txtTiennuoc;
    private javax.swing.JTextField txtTongtien;
    // End of variables declaration//GEN-END:variables
}
