/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.Daocudan;
import DAO.Daoguiyc;
import MODEL.Modelcudan;
import MODEL.Modelyeucaucd;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thinkbook 16
 */
public class Viewguiyc extends javax.swing.JFrame {
    private String ma;
    private DefaultTableModel tblModel;
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    
    public Viewguiyc(String macd) {
        initComponents();
        jTableYeucau.setDefaultEditor(Object.class, null);
        initTable();
        this.setLocationRelativeTo(null);
        ma = macd;
        loadDataToTable();
        
    }
    
     public final void initTable() {
        tblModel = new DefaultTableModel();
        String[] headerTbl = new String[]{"Mã Yêu Cầu", "Loại Yêu Cầu", "Nội Dung"};
        tblModel.setColumnIdentifiers(headerTbl);
        jTableYeucau.setModel(tblModel);
        
        jTableYeucau.setRowHeight(25);
        jTableYeucau.setFont(new Font("Arial", Font.PLAIN, 12));

        // Alternating row colors
        jTableYeucau.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (isSelected) {
                    c.setBackground(new Color(0, 120, 215)); // Màu nền cho hàng được chọn (thay đổi nếu cần)
                    c.setForeground(Color.WHITE); // Màu chữ cho hàng được chọn (thay đổi nếu cần)
                } else {
                    c.setBackground(row % 2 == 0 ? Color.LIGHT_GRAY : Color.WHITE);
                    c.setForeground(Color.BLACK); // Màu chữ cho hàng không được chọn
                }
                return c;
            }
        });
        
        
        
        
        
        
        jTableYeucau.getColumnModel().getColumn(0).setPreferredWidth(20);
        jTableYeucau.getColumnModel().getColumn(1).setPreferredWidth(40);
        jTableYeucau.getColumnModel().getColumn(2).setPreferredWidth(40); 
    }    
    
    
    public MODEL.Modelyeucaucd getDetail() {
        MODEL.Modelyeucaucd a = Daoguiyc.getInstance().selectById(getYEUCAUSelect().getMAYC());
        return a;
    }
    public MODEL.Modelyeucaucd getYEUCAUSelect() {
        int i_row = jTableYeucau.getSelectedRow();
        MODEL.Modelyeucaucd yc = Daoguiyc.getInstance().selectAll().get(i_row);
        return yc;
    }
    public void loadDataToTable() {
        try {
            Daoguiyc daoyc = new Daoguiyc();
            ArrayList<MODEL.Modelyeucaucd> arms = daoyc.selectByMACD(ma);
            tblModel.setRowCount(0);
            for (MODEL.Modelyeucaucd i : arms ) {
                tblModel.addRow(new Object[]{
                i.getMAYC(), i.getLoaiYC(),i.getNoiDungYC()    
            }
            );
        }
    } catch (Exception e) {
        System.err.println(e.toString());
       }
}
    
    public String createId() {
    ArrayList<Modelyeucaucd> ycAll = Daoguiyc.getInstance().selectAll();
    int maxId = 0;
    for (Modelyeucaucd yc : ycAll) {
        String MAYC = yc.getMAYC();
        if (MAYC.startsWith("YC")) {
            try {
                int id = Integer.parseInt(MAYC.replaceAll("[^\\d]", ""));
                if (id > maxId) {
                    maxId = id;
                }
            } catch (NumberFormatException e) {
            }
        }
    }
    return  (String.format("YC%03d", maxId + 1));
}
    
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        labelLoaiyc = new javax.swing.JLabel();
        btnGui = new javax.swing.JButton();
        btnQuaylai = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelGuiyc = new javax.swing.JLabel();
        CBLoaiyc = new javax.swing.JComboBox<>();
        labelNoidung = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoidung = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableYeucau = new javax.swing.JTable();
        labelLichsu = new javax.swing.JLabel();
        btnXoayc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(55, 139, 167));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelLoaiyc.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelLoaiyc.setForeground(new java.awt.Color(255, 255, 255));
        labelLoaiyc.setText("Loại yêu cầu");

        btnGui.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-email-send-48.png"))); // NOI18N
        btnGui.setText("Gửi");
        btnGui.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGui.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuiMouseClicked(evt);
            }
        });
        btnGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiActionPerformed(evt);
            }
        });

        btnQuaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-left-50.png"))); // NOI18N
        btnQuaylai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaylaiActionPerformed(evt);
            }
        });

        labelGuiyc.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        labelGuiyc.setForeground(new java.awt.Color(255, 255, 255));
        labelGuiyc.setText("PHIẾU HỖ TRỢ");

        CBLoaiyc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yeu cau sua chua", "Yeu cau ve sinh", "Yeu cau bao tri", "Yeu cau ho tro", "Yeu cau gop y" }));
        CBLoaiyc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        labelNoidung.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelNoidung.setForeground(new java.awt.Color(255, 255, 255));
        labelNoidung.setText("Nội dung");

        txtNoidung.setColumns(20);
        txtNoidung.setRows(5);
        txtNoidung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(txtNoidung);

        jTableYeucau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Yêu Cầu", "Loại Yêu Cầu", "Nội Dung"
            }
        ));
        jTableYeucau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane2.setViewportView(jTableYeucau);

        labelLichsu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelLichsu.setForeground(new java.awt.Color(255, 255, 255));
        labelLichsu.setText("Lịch sử yêu cầu");

        btnXoayc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-30.png"))); // NOI18N
        btnXoayc.setText("Xóa");
        btnXoayc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoayc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaycActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-support-94.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelNoidung, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGui))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelLoaiyc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelLichsu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(CBLoaiyc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoayc))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnQuaylai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelGuiyc)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel2)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelGuiyc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnQuaylai, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(labelLichsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoayc)
                .addGap(0, 0, 0)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLoaiyc)
                    .addComponent(CBLoaiyc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNoidung))))
                .addGap(18, 18, 18)
                .addComponent(btnGui, javax.swing.GroupLayout.PREFERRED_SIZE, 43, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuiMouseClicked

    private void btnGuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiActionPerformed
     try {
        String loaiyc = CBLoaiyc.getSelectedItem().toString();
        String noidung = txtNoidung.getText();
        String i = createId();
               
        // Create a ModelCanho object with the retrieved data
        Modelyeucaucd yc = new Modelyeucaucd(i , loaiyc, noidung, "Chua xu ly",ma);
        Daoguiyc gui = new Daoguiyc();
        
        // Call the addcanho method of your DAO class to add the Canho
        gui.addyeucau(yc);
        
        // Optionally display a success message or update UI
        JOptionPane.showMessageDialog(null, "Yêu cầu đã được gửi thành công!");
        
        txtNoidung.setText("");
        loadDataToTable();
    } catch (Exception ex) {
        // Handle any errors or exceptions (e.g., display error message)
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi gửi yêu cầu: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnGuiActionPerformed

    private void btnQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaylaiActionPerformed
        ViewMenucudan menucd=new ViewMenucudan(ma);
        menucd.show();
        dispose();
    }//GEN-LAST:event_btnQuaylaiActionPerformed

    private void btnXoaycActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaycActionPerformed
             if (jTableYeucau.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn yêu cầu muốn xoá");
        } else {
            int output = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xoá yêu cầu", "Xác nhận xoá yêu cầu", JOptionPane.YES_NO_OPTION);
            if (output == JOptionPane.YES_OPTION) {
                Daoguiyc.getInstance().delete(getYEUCAUSelect());
                JOptionPane.showMessageDialog(this, "Xóa thành công !");
                loadDataToTable();
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaycActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Viewguiyc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Viewguiyc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Viewguiyc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Viewguiyc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Viewguiyc().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBLoaiyc;
    private javax.swing.JButton btnGui;
    private javax.swing.JButton btnQuaylai;
    private javax.swing.JButton btnXoayc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableYeucau;
    private javax.swing.JLabel labelGuiyc;
    private javax.swing.JLabel labelLichsu;
    private javax.swing.JLabel labelLoaiyc;
    private javax.swing.JLabel labelNoidung;
    private javax.swing.JTextArea txtNoidung;
    // End of variables declaration//GEN-END:variables
}
