/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;



import DAO.Daoxe;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.BorderLayout;
import java.awt.event.*;
import java.util.ArrayList;
import java.text.DecimalFormat;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.TableColumn;
import MODEL.Modelxe;
import controler.Timxe;
/**
 *
 * @author hoangxuanthuy
 */
public class Viewxe extends javax.swing.JFrame {

    private DefaultTableModel tblModel;
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    public Viewxe() {
        initComponents();
         jTableXe.setDefaultEditor(Object.class, null);
              initTable();
               this.setLocationRelativeTo(null);
       loadDataToTable();
    }
     public final void initTable() {
        tblModel = new DefaultTableModel();
        String[] headerTbl = new String[]{"Mã Xe", "Biển Số Xe", "Loại Xe", "Mã Cư Dân"};
        tblModel.setColumnIdentifiers(headerTbl);
        jTableXe.setModel(tblModel);
        jTableXe.getColumnModel().getColumn(0).setPreferredWidth(40);
        jTableXe.getColumnModel().getColumn(1).setPreferredWidth(40);
        jTableXe.getColumnModel().getColumn(2).setPreferredWidth(40);
        jTableXe.getColumnModel().getColumn(3).setPreferredWidth(40);
   
       
        
    }
      public void changeTextFind() {
        txttracuu.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {

            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                /* do nothing */
                if (txttracuu.getText().length() == 0) {
                    loadDataToTable();
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                /* do nothing */

            }
        });
    }
    public ArrayList<Modelxe> searchFn(String luaChon, String content) {
        ArrayList<MODEL.Modelxe> result = new ArrayList<>();
        Timxe timcd = new Timxe();
        switch (luaChon) {
            case "MAXE":
                result = timcd.searchMAXE(content);
                break;
            case "BIENSOXE":
                result = timcd.searchBSX(content);
                break;
            
        }
        return result;
    }
    public MODEL.Modelxe getDetail() {
        MODEL.Modelxe a = Daoxe.getInstance().selectById(getXESelect().getMaXe());
        return a;
    }
    public MODEL.Modelxe getXESelect() {
        int i_row = jTableXe.getSelectedRow();
        MODEL.Modelxe cd = Daoxe.getInstance().selectAll().get(i_row);
        return cd;
    }
     public void loadDataToTable() {
    try {
        Daoxe cddao = new Daoxe();
        ArrayList<MODEL.Modelxe> arms = cddao.selectAll();
        tblModel.setRowCount(0);
        for (MODEL.Modelxe i : arms ) {
            tblModel.addRow(new Object[]{
                    i.getMaXe(), i.getBienSoXe(),i.getLoaiXe(),i.getMaCD()           
            }
            );
        }
    } catch (Exception e) {
        System.err.println(e.toString());
        
    }
}
     public void loadDataToTableSearch(ArrayList<MODEL.Modelxe> result) {
        try {
            tblModel.setRowCount(0);
            for (MODEL.Modelxe i : result) {
                tblModel.addRow(new Object[]{
                   i.getMaXe(), i.getBienSoXe(),i.getLoaiXe(),i.getMaCD()          
                }
                );
            }
        } catch (Exception e) {  
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnthemxe = new javax.swing.JButton();
        btnxoaxe = new javax.swing.JButton();
        btnsuaxe = new javax.swing.JButton();
        btntracuu = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableXe = new javax.swing.JTable();
        labQLXE = new javax.swing.JLabel();
        txttracuu = new javax.swing.JTextField();
        jButtontrangchu = new javax.swing.JButton();
        jComboluachon = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(196, 233, 245));

        jPanel2.setBackground(new java.awt.Color(55, 139, 167));
        jPanel2.setForeground(new java.awt.Color(196, 233, 245));

        btnthemxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-30.png"))); // NOI18N
        btnthemxe.setText("Thêm");
        btnthemxe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnthemxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemxeActionPerformed(evt);
            }
        });

        btnxoaxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-delete-30.png"))); // NOI18N
        btnxoaxe.setText("Xóa");
        btnxoaxe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnxoaxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaxeActionPerformed(evt);
            }
        });

        btnsuaxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-update-item (2).png"))); // NOI18N
        btnsuaxe.setText("Sửa");
        btnsuaxe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsuaxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaxeActionPerformed(evt);
            }
        });

        btntracuu.setBackground(new java.awt.Color(55, 139, 167));
        btntracuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-36.png"))); // NOI18N
        btntracuu.setBorder(null);
        btntracuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btntracuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntracuuMouseClicked(evt);
            }
        });
        btntracuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntracuuActionPerformed(evt);
            }
        });

        jTableXe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Xe", "Biển số xe", "Loại Xe", "Mã Chủ Xe"
            }
        ));
        jTableXe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTableXe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableXeMouseClicked(evt);
            }
        });
        jTableXe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableXeKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableXe);

        labQLXE.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labQLXE.setForeground(new java.awt.Color(255, 255, 255));
        labQLXE.setText("QUẢN LÝ XE");

        txttracuu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txttracuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttracuuActionPerformed(evt);
            }
        });

        jButtontrangchu.setBackground(new java.awt.Color(55, 139, 167));
        jButtontrangchu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtontrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-home-48.png"))); // NOI18N
        jButtontrangchu.setBorder(null);
        jButtontrangchu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtontrangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontrangchuActionPerformed(evt);
            }
        });

        jComboluachon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MAXE", "BIENSOXE", " " }));
        jComboluachon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboluachon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboluachonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboluachon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttracuu, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btntracuu)
                .addGap(283, 283, 283))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(btnthemxe)
                        .addGap(60, 60, 60)
                        .addComponent(btnsuaxe)
                        .addGap(51, 51, 51)
                        .addComponent(btnxoaxe))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtontrangchu)
                        .addGap(341, 341, 341)
                        .addComponent(labQLXE)))
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labQLXE))
                    .addComponent(jButtontrangchu))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntracuu)
                    .addComponent(txttracuu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboluachon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsuaxe)
                    .addComponent(btnthemxe)
                    .addComponent(btnxoaxe))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemxeActionPerformed
        Viewthemxe viewxe=new Viewthemxe();
        viewxe.show();
        dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_btnthemxeActionPerformed

    private void btnxoaxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaxeActionPerformed
        if (jTableXe.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn xe muốn xoá");
        } else {
            int output = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xoá xe", "Xác nhận xoá xe", JOptionPane.YES_NO_OPTION);
            if (output == JOptionPane.YES_OPTION) {
                Daoxe.getInstance().delete(getXESelect());
                JOptionPane.showMessageDialog(this, "Xóa thành công !");
                loadDataToTable();
            }
        }
    }//GEN-LAST:event_btnxoaxeActionPerformed

    private void btnsuaxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaxeActionPerformed
        if (jTableXe.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn xe cần sửa thông tin");
        } else {
            Viewsuaxe frame = new Viewsuaxe(this);
            frame.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnsuaxeActionPerformed

    private void btntracuuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntracuuMouseClicked

        // TODO add your handling code here:
        String luaChon = jComboluachon.getSelectedItem().toString();
        String content = txttracuu.getText();
        ArrayList<MODEL.Modelxe> result = searchFn(luaChon, content);
        loadDataToTableSearch(result);
    }//GEN-LAST:event_btntracuuMouseClicked

    private void btntracuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntracuuActionPerformed
        
        loadDataToTable();
    }//GEN-LAST:event_btntracuuActionPerformed

    private void jTableXeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableXeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableXeMouseClicked

    private void jTableXeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableXeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableXeKeyReleased

    private void txttracuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttracuuActionPerformed
        // TODO add your handling code here:
        String luaChon = jComboluachon.getSelectedItem().toString();
        String content = txttracuu.getText();
        ArrayList<MODEL.Modelxe> result = searchFn(luaChon, content);
        loadDataToTableSearch(result);
    }//GEN-LAST:event_txttracuuActionPerformed

    private void jButtontrangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontrangchuActionPerformed
        ViewMenubql viewbql= new ViewMenubql();
        viewbql.show();
        dispose();       // TODO add your handling code here:
    }//GEN-LAST:event_jButtontrangchuActionPerformed

    private void jComboluachonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboluachonActionPerformed
        // TODO add your handling code here:
        String luaChon = jComboluachon.getSelectedItem().toString();
        String content = txttracuu.getText();
        ArrayList<MODEL.Modelxe> result = searchFn(luaChon, content);
        loadDataToTableSearch(result);
    }//GEN-LAST:event_jComboluachonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewxe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsuaxe;
    private javax.swing.JButton btnthemxe;
    private javax.swing.JButton btntracuu;
    private javax.swing.JButton btnxoaxe;
    private javax.swing.JButton jButtontrangchu;
    private javax.swing.JComboBox<String> jComboluachon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableXe;
    private javax.swing.JLabel labQLXE;
    private javax.swing.JTextField txttracuu;
    // End of variables declaration//GEN-END:variables
}
