/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;


import DAO.Daohopdong;
import MODEL.Modelhopdong;
import javax.swing.JOptionPane;
import View.Viewhopdong;
import java.awt.Frame;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTextField;
/**
 *
 * @author Thinkbook 16
 */
public class Viewsuahopdong extends javax.swing.JFrame {
        private Viewhopdong owner;
    public Viewsuahopdong() {
        super();
        initComponents();
        setLocationRelativeTo(null);
    }
    /**
     * Creates new form Viewsuahopdong
     */
   public Viewsuahopdong(Viewhopdong parent) {
        super();  // gọi constructor của JFrame
        initComponents();
        setLocationRelativeTo(null);
        this.owner = parent;
        Modelhopdong hd = this.owner.getDetail();
        
        txtMahopdong.setText(hd.getMAHOPDONG().trim());
        txtNgaybd.setText(hd.getNGAYBD().trim());
        txtThoihan.setText(hd.getTHOIHAN().trim());
        CBLoaihopdong.setSelectedItem(hd.getLOAIHD());
        txtGia.setText(hd.getGIA() + " ");
        txtMacd.setText(hd.getMACD().trim());
        txtMabql.setText(hd.getMABQL().trim());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMahopdong = new javax.swing.JLabel();
        jLabelNgaybd = new javax.swing.JLabel();
        jLabelThoihan = new javax.swing.JLabel();
        jLabelLoaihopdong = new javax.swing.JLabel();
        jLabelGia = new javax.swing.JLabel();
        jLabelMabql = new javax.swing.JLabel();
        jLabelMacd = new javax.swing.JLabel();
        txtMahopdong = new javax.swing.JTextField();
        txtNgaybd = new javax.swing.JTextField();
        txtThoihan = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        txtMacd = new javax.swing.JTextField();
        txtMabql = new javax.swing.JTextField();
        CBLoaihopdong = new javax.swing.JComboBox<>();
        btnSuahopdong = new javax.swing.JButton();
        btnResethopdong = new javax.swing.JButton();
        btnQuaylai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 139, 167));
        jPanel1.setForeground(null);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelMahopdong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMahopdong.setForeground(java.awt.Color.white);
        jLabelMahopdong.setText("Mã Hợp Đồng");

        jLabelNgaybd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelNgaybd.setForeground(java.awt.Color.white);
        jLabelNgaybd.setText("Ngày Bắt Đầu");

        jLabelThoihan.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelThoihan.setForeground(java.awt.Color.white);
        jLabelThoihan.setText("Thời Hạn");

        jLabelLoaihopdong.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelLoaihopdong.setForeground(java.awt.Color.white);
        jLabelLoaihopdong.setText("Loại Hợp Đồng");

        jLabelGia.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGia.setForeground(java.awt.Color.white);
        jLabelGia.setText("Giá");

        jLabelMabql.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMabql.setForeground(java.awt.Color.white);
        jLabelMabql.setText("Mã Ban Quản Lý");

        jLabelMacd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMacd.setForeground(java.awt.Color.white);
        jLabelMacd.setText("Mã Cư Dân");

        txtMahopdong.setEditable(false);
        txtMahopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMahopdongActionPerformed(evt);
            }
        });

        txtNgaybd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgaybdActionPerformed(evt);
            }
        });

        CBLoaihopdong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hop dong thue nha", "Hop dong mua nha", " " }));
        CBLoaihopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBLoaihopdongActionPerformed(evt);
            }
        });

        btnSuahopdong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-update-item (2).png"))); // NOI18N
        btnSuahopdong.setText("Sửa");
        btnSuahopdong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSuahopdongMouseClicked(evt);
            }
        });
        btnSuahopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuahopdongActionPerformed(evt);
            }
        });

        btnResethopdong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-update-30 (1).png"))); // NOI18N
        btnResethopdong.setText("Reset");
        btnResethopdong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResethopdongActionPerformed(evt);
            }
        });

        btnQuaylai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-left-50.png"))); // NOI18N
        btnQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaylaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnSuahopdong)
                        .addGap(45, 45, 45)
                        .addComponent(btnResethopdong))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelLoaihopdong, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jLabelGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelMabql)
                            .addComponent(jLabelMacd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNgaybd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelMahopdong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelThoihan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtThoihan, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBLoaihopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMahopdong, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgaybd, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMacd, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMabql, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnQuaylai))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnQuaylai)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMahopdong)
                    .addComponent(txtMahopdong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNgaybd)
                    .addComponent(txtNgaybd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelThoihan)
                    .addComponent(txtThoihan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLoaihopdong)
                    .addComponent(CBLoaihopdong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGia)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMacd)
                    .addComponent(txtMacd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMabql)
                    .addComponent(txtMabql, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuahopdong)
                    .addComponent(btnResethopdong))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMahopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMahopdongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMahopdongActionPerformed

    private void txtNgaybdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgaybdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgaybdActionPerformed

    private void CBLoaihopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBLoaihopdongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBLoaihopdongActionPerformed

    private void btnSuahopdongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSuahopdongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSuahopdongMouseClicked

    private void btnSuahopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuahopdongActionPerformed
        Daohopdong hd = new Daohopdong();
        Modelhopdong s = new Modelhopdong();
        
        s.setMAHOPDONG(txtMahopdong.getText());
        s.setNGAYBD(txtNgaybd.getText());
        s.setTHOIHAN(txtThoihan.getText());
        String selectedValue = (String) CBLoaihopdong.getSelectedItem();
        if ("Hop dong thue nha".equals(selectedValue)) {
            s.setLOAIHD("Hop dong thue nha");
        } else {
            s.setLOAIHD("Hop dong mua nha");
}
      //  s.setLOAIHD(CBLoaihopdong.);
        s.setGIA (Double.parseDouble(txtGia.getText()));
        s.setMACD(txtMacd.getText());
        s.setMABQL(txtMabql.getText());
        
        
        
             
        try {
            hd.update(s);
        } catch (SQLException ex) {
            Logger.getLogger(Viewsuahopdong.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Viewsuahopdong.class.getName()).log(Level.SEVERE, null, ex);
        }
        new Viewhopdong().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSuahopdongActionPerformed

    private void btnResethopdongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResethopdongActionPerformed
        txtNgaybd.setText("");
        txtThoihan.setText("");
        txtGia.setText("");
        txtMacd.setText("");
        txtMabql.setText("");
        
    }//GEN-LAST:event_btnResethopdongActionPerformed

    private void btnQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaylaiActionPerformed
        Viewhopdong viewhd=new Viewhopdong();
        viewhd.show();
        dispose();
    }//GEN-LAST:event_btnQuaylaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewsuahopdong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewsuahopdong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewsuahopdong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewsuahopdong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewsuahopdong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBLoaihopdong;
    private javax.swing.JButton btnQuaylai;
    private javax.swing.JButton btnResethopdong;
    private javax.swing.JButton btnSuahopdong;
    private javax.swing.JLabel jLabelGia;
    private javax.swing.JLabel jLabelLoaihopdong;
    private javax.swing.JLabel jLabelMabql;
    private javax.swing.JLabel jLabelMacd;
    private javax.swing.JLabel jLabelMahopdong;
    private javax.swing.JLabel jLabelNgaybd;
    private javax.swing.JLabel jLabelThoihan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMabql;
    private javax.swing.JTextField txtMacd;
    private javax.swing.JTextField txtMahopdong;
    private javax.swing.JTextField txtNgaybd;
    private javax.swing.JTextField txtThoihan;
    // End of variables declaration//GEN-END:variables
}
