/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import MODEL.Modelcanho;
import DAO.Daocanho;
import View.Viewcanho;

/**
 *
 * @author HP
 */
public class Viewthemcanho extends javax.swing.JFrame {

   
    public Viewthemcanho() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMach = new javax.swing.JLabel();
        jLabelDientich = new javax.swing.JLabel();
        jLabelLoaiCH = new javax.swing.JLabel();
        jLabelSopngu = new javax.swing.JLabel();
        jLabelSoptam = new javax.swing.JLabel();
        jLabelPhidichvu = new javax.swing.JLabel();
        jLableSlxe = new javax.swing.JLabel();
        jLabelGiathue = new javax.swing.JLabel();
        jLabelTang = new javax.swing.JLabel();
        jLabelGiaxe = new javax.swing.JLabel();
        txtMach = new javax.swing.JTextField();
        txtDientich = new javax.swing.JTextField();
        txtSophongngu = new javax.swing.JTextField();
        txtSophongtam = new javax.swing.JTextField();
        txtTang = new javax.swing.JTextField();
        txtGiathue = new javax.swing.JTextField();
        txtPhidichvu = new javax.swing.JTextField();
        txtSoluongxe = new javax.swing.JTextField();
        txtGiaxe = new javax.swing.JTextField();
        CBLoaicanho = new javax.swing.JComboBox<>();
        btnThemcanho = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtmacd = new javax.swing.JTextField();
        txtmanv = new javax.swing.JTextField();
        txtmahd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(196, 233, 245));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelMach.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMach.setText("Mã căn hộ");

        jLabelDientich.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelDientich.setText("Diện tích");

        jLabelLoaiCH.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelLoaiCH.setText("Loại căn hộ");

        jLabelSopngu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSopngu.setText("Số Phòng Ngủ");

        jLabelSoptam.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelSoptam.setText("Số Phòng Tắm");

        jLabelPhidichvu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelPhidichvu.setText("Phí Dịch Vụ");

        jLableSlxe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLableSlxe.setText("Số Lượng Xe");

        jLabelGiathue.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGiathue.setText("Giá Thuê");

        jLabelTang.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelTang.setText("Tầng");

        jLabelGiaxe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelGiaxe.setText("Giá Xe");

        txtMach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMachActionPerformed(evt);
            }
        });

        txtDientich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDientichActionPerformed(evt);
            }
        });

        CBLoaicanho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thường", "Studio", " ", " " }));
        CBLoaicanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBLoaicanhoActionPerformed(evt);
            }
        });

        btnThemcanho.setText("Thêm");
        btnThemcanho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemcanhoMouseClicked(evt);
            }
        });
        btnThemcanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemcanhoActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jButton3.setText("Quay lại");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Mã Nhân Viên");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Mã Cư Dân");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Mã Hợp Đồng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDientich, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLoaiCH, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSopngu, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSoptam, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTang, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGiathue)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelPhidichvu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLableSlxe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabelGiaxe, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabelMach, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnThemcanho)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnReset)
                        .addGap(43, 43, 43)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtmanv, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtmacd, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDientich)
                                .addComponent(txtSophongngu)
                                .addComponent(txtMach)
                                .addComponent(txtSophongtam)
                                .addComponent(txtTang)
                                .addComponent(txtGiathue)
                                .addComponent(txtPhidichvu)
                                .addComponent(txtSoluongxe)
                                .addComponent(txtGiaxe)
                                .addComponent(CBLoaicanho, 0, 188, Short.MAX_VALUE))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(txtmahd)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMach)
                    .addComponent(txtMach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDientich)
                    .addComponent(txtDientich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLoaiCH)
                    .addComponent(CBLoaicanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSopngu)
                    .addComponent(txtSophongngu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSoptam)
                    .addComponent(txtSophongtam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTang)
                    .addComponent(txtTang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGiathue)
                    .addComponent(txtGiathue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhidichvu)
                    .addComponent(txtPhidichvu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLableSlxe)
                    .addComponent(txtSoluongxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGiaxe)
                    .addComponent(txtGiaxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmacd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtmahd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemcanho)
                    .addComponent(btnReset)
                    .addComponent(jButton3))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDientichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDientichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDientichActionPerformed

    private void CBLoaicanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBLoaicanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBLoaicanhoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Viewcanho viewch=new Viewcanho();
            viewch.show();
            dispose();          
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtMach.setText("");
        txtDientich.setText("");
        txtGiathue.setText("");
        txtGiaxe.setText("");
        txtSophongngu.setText("");
        txtSophongtam.setText("");
        txtTang.setText("");
        txtPhidichvu.setText("");
        txtSoluongxe.setText("");
        txtmacd.setText("");
        txtmahd.setText("");
        txtmanv.setText("");
    }//GEN-LAST:event_btnResetActionPerformed
    
    private void txtMachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMachActionPerformed

    private void btnThemcanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemcanhoActionPerformed
       try {
        String mach = txtMach.getText();
        double dienTich = Double.parseDouble(txtDientich.getText());
        String loaich = CBLoaicanho.getSelectedItem().toString();
        int spn = Integer.parseInt(txtSophongngu.getText());
        int spt = Integer.parseInt(txtSophongtam.getText());
        int tang = Integer.parseInt(txtTang.getText());
        double giathue = Double.parseDouble(txtGiathue.getText());
        double phidv = Double.parseDouble(txtPhidichvu.getText());
        double giaxe = Double.parseDouble(txtGiaxe.getText());
        int slxe = Integer.parseInt(txtSoluongxe.getText());
        String macd = txtmacd.getText();
        String manv = txtmanv.getText();
        String mahd = txtmahd.getText();
        
        // Create a ModelCanho object with the retrieved data
        Modelcanho ch = new Modelcanho(mach, dienTich, loaich, spn, spt, tang, giathue, phidv, giaxe, slxe, macd, manv, mahd);
        Daocanho them = new Daocanho();
        
        // Call the addcanho method of your DAO class to add the Canho
        them.addcanho(ch);
        
        // Optionally display a success message or update UI
        JOptionPane.showMessageDialog(null, "Căn hộ đã được thêm thành công!");

        // Optionally clear input fields or update UI
        Viewcanho viewch= new Viewcanho();
        viewch.show();
        dispose(); 
        
        
        // Update UI to reflect changes
        // You may need to refresh the table or list displaying the data
        
    } catch (Exception ex) {
        // Handle any errors or exceptions (e.g., display error message)
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi thêm căn hộ: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnThemcanhoActionPerformed

    private void btnThemcanhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemcanhoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemcanhoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewthemcanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewthemcanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewthemcanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewthemcanho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewthemcanho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBLoaicanho;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThemcanho;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDientich;
    private javax.swing.JLabel jLabelGiathue;
    private javax.swing.JLabel jLabelGiaxe;
    private javax.swing.JLabel jLabelLoaiCH;
    private javax.swing.JLabel jLabelMach;
    private javax.swing.JLabel jLabelPhidichvu;
    private javax.swing.JLabel jLabelSopngu;
    private javax.swing.JLabel jLabelSoptam;
    private javax.swing.JLabel jLabelTang;
    private javax.swing.JLabel jLableSlxe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtDientich;
    private javax.swing.JTextField txtGiathue;
    private javax.swing.JTextField txtGiaxe;
    private javax.swing.JTextField txtMach;
    private javax.swing.JTextField txtPhidichvu;
    private javax.swing.JTextField txtSoluongxe;
    private javax.swing.JTextField txtSophongngu;
    private javax.swing.JTextField txtSophongtam;
    private javax.swing.JTextField txtTang;
    private javax.swing.JTextField txtmacd;
    private javax.swing.JTextField txtmahd;
    private javax.swing.JTextField txtmanv;
    // End of variables declaration//GEN-END:variables
}
