/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import MODEL.Modelxe;
import DAO.Daoxe;
import View.Viewxe;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
public class Viewthemxe extends javax.swing.JFrame {

    /**
     * Creates new form Viewthemxe
     */
    public Viewthemxe() {
         initComponents();
        this.setLocationRelativeTo(null);
        txtmaxe.setText(createId());
    }
    public String createId() {
        ArrayList<Modelxe> cdAll = Daoxe.getInstance().selectAll();
        int maxId = 0;
        for (Modelxe cd : cdAll) {
            String MAXE = cd.getMaXe();
            if (MAXE.startsWith("XE")) {
                try {
                int id = Integer.parseInt(MAXE.replaceAll("[^\\d]", ""));
                if (id > maxId) {
                    maxId = id;
                    }
                } catch (NumberFormatException e) {
                }
            }
        }
        return  (String.format("XE%03d", maxId + 1));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMaxe = new javax.swing.JLabel();
        jLabelbsoxe = new javax.swing.JLabel();
        jLabelLoaixe = new javax.swing.JLabel();
        labelmacd = new javax.swing.JLabel();
        txtmaxe = new javax.swing.JTextField();
        txtbiensoxe = new javax.swing.JTextField();
        txtmacd = new javax.swing.JTextField();
        txtloaixe = new javax.swing.JTextField();
        btnThemxe = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 139, 167));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelMaxe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelMaxe.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMaxe.setText("Mã Xe");

        jLabelbsoxe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelbsoxe.setForeground(new java.awt.Color(255, 255, 255));
        jLabelbsoxe.setText("Biển Số Xe");

        jLabelLoaixe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelLoaixe.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoaixe.setText("Loại Xe");

        labelmacd.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelmacd.setForeground(new java.awt.Color(255, 255, 255));
        labelmacd.setText("Mã Cư Dân");

        txtmaxe.setEditable(false);
        txtmaxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmaxeActionPerformed(evt);
            }
        });

        txtbiensoxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbiensoxeActionPerformed(evt);
            }
        });

        btnThemxe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-update-item (2).png"))); // NOI18N
        btnThemxe.setText("Thêm");
        btnThemxe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemxe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemxeMouseClicked(evt);
            }
        });
        btnThemxe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemxeActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-update-30 (1).png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-left-50.png"))); // NOI18N
        jButton3.setToolTipText("");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnThemxe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelMaxe, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelLoaixe, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabelbsoxe, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelmacd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbiensoxe, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtloaixe, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmaxe, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmacd, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaxe)
                    .addComponent(txtmaxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelbsoxe)
                    .addComponent(txtbiensoxe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLoaixe)
                    .addComponent(txtloaixe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelmacd)
                    .addComponent(txtmacd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemxe, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Viewxe viewxe=new Viewxe();
        viewxe.show();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed

        txtbiensoxe.setText("");
        txtloaixe.setText("");
        txtmacd.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnThemxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemxeActionPerformed
        try {
            String Macd = txtmaxe.getText();
            String bsx =txtbiensoxe.getText();
            String loaixe = txtloaixe.getText();
            String macd = txtmacd.getText();
            // Create a ModelCanho object with the retrieved data
            Modelxe xe = new Modelxe(Macd,bsx,loaixe,macd);
            Daoxe them = new Daoxe();

            // Call the addcanho method of your DAO class to add the Canho
            them.addxe(xe);

            // Optionally display a success message or update UI
            JOptionPane.showMessageDialog(null, "Xe đã được thêm thành công!");

            // Optionally clear input fields or update UI
            Viewxe viewxe= new Viewxe();
            viewxe.show();
            dispose();

            // Update UI to reflect changes
            // You may need to refresh the table or list displaying the data

        } catch (Exception ex) {
            // Handle any errors or exceptions (e.g., display error message)
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi khi thêm xe: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemxeActionPerformed

    private void btnThemxeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemxeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemxeMouseClicked

    private void txtbiensoxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbiensoxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbiensoxeActionPerformed

    private void txtmaxeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmaxeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmaxeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Viewthemxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Viewthemxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Viewthemxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Viewthemxe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Viewthemxe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThemxe;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabelLoaixe;
    private javax.swing.JLabel jLabelMaxe;
    private javax.swing.JLabel jLabelbsoxe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelmacd;
    private javax.swing.JTextField txtbiensoxe;
    private javax.swing.JTextField txtloaixe;
    private javax.swing.JTextField txtmacd;
    private javax.swing.JTextField txtmaxe;
    // End of variables declaration//GEN-END:variables
}
